---
- hosts: all

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.gunicorn" }
    - { role: "gunicorn.example" }

  vars:
    gunicorn_bind: "0.0.0.0:8000"
    gunicorn_app_dir: /home/gunicorn
    gunicorn_wsgi: hello_world
